USE PasteleriaDB;
-- SHOW FULL TABLES FROM PasteleriaDB;
-- SELECT * FROM Usuario;

-- INSERT INTO Tamano(nombre, numPersonas) VALUES('Chico', 8);
-- INSERT INTO Tamano(nombre, numPersonas) VALUES('Mediano', 16);
-- INSERT INTO Tamano(nombre, numPersonas) VALUES('Grande', 20);
-- INSERT INTO Tamano(nombre, numPersonas) VALUES('King', 25);
-- INSERT INTO Tamano(nombre, numPersonas) VALUES('Dios', 35);
-- INSERT INTO Sabor(nombre) VALUES('Vainilla');
-- INSERT INTO Sabor(nombre) VALUES('Chocolate');
-- INSERT INTO Sabor(nombre) VALUES('Fresa');
-- INSERT INTO Sabor(nombre) VALUES('Durazno');
-- INSERT INTO Sabor(nombre) VALUES('Piña');
-- INSERT INTO Sabor(nombre) VALUES('Nuez');
-- INSERT INTO Tipo(nombre) VALUES('Seco');
-- INSERT INTO Tipo(nombre) VALUES('Tres leches');
-- INSERT INTO Tipo(nombre) VALUES('Media leche');
-- INSERT INTO Tipo(nombre) VALUES('Empapado');
-- INSERT INTO Cubierta(nombre) VALUES('Merengue');
-- INSERT INTO Cubierta(nombre) VALUES('Fondant');
-- INSERT INTO Cubierta(nombre) VALUES('Glaseado');
-- INSERT INTO Cubierta(nombre) VALUES('Fruti Lupis');
-- INSERT INTO Pastel(nombre, saborID, tipoID, precio, cubiertaID, tamanoID, existencias, clave, imgRef) VALUES('Rocket Mars', 1, 2, 400.50, 2, 3, 12, 'RCKTMRS456', 'https://imageneslibres.org/carros/carcachas/carreta,jpg');
-- INSERT INTO Pastel(nombre, saborID, tipoID, precio, cubiertaID, tamanoID, existencias, clave, imgRef) VALUES('Futbol', 2, 1, 350.50, 2, 2, 12, 'RCKT4RS456', 'https://imageneslibres.org/carros/carcachas/carreta,jpg');
-- INSERT INTO Pastel(nombre, saborID, tipoID, precio, cubiertaID, tamanoID, existencias, clave, imgRef) VALUES('Queroro', 3, 1, 400.50, 1, 3, 12, '6RCK5RS456', 'https://imageneslibres.org/carros/carcachas/carreta,jpg');

SELECT a.nombre, c.nombre AS sabor, b.nombre AS tipo, a.precio, d.nombre AS cubierta, e.nombre AS tamaño, e.numPersonas AS numPerson, a.existencias, a.clave, a.imgRef FROM Pastel a, Tipo b, Sabor c, Cubierta d, Tamano e WHERE a.saborID = c.saborID AND a.tipoID = b.tipoID AND a.cubiertaID = d.cubiertaID AND a.tamanoID = e.tamanoID ;
SELECT * FROM Cubierta;
SELECT * FROM Tipo;
SELECT * FROM Tamano;
SELECT * FROM Sabor;